name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.8"
          channel: "stable"
      - name: Run lint
        run: flutter analyze
      - name: Run tests
        run: flutter test
